AnatidaeHaxball/Controllers/AdminController.cs
using AnatidaeHaxball.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AnatidaeHaxball.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Admin/Jogadores/

        public ActionResult Jogadores()
        {
            return View(AppServices.GetAllJogadoresDaEquipa());
        }

        //
        // GET: /Admin/Create

        public ActionResult CreateJogador()
        {
            return View(new JogadorModels());
        }

        //
        // POST: /Admin/Create

        [HttpPost]
        public ActionResult CreateJogador(Jogador jogador)
        {
            try
            {
                jogador.nomeShirt = DataUtils.CreateJogadorShirt(
                    HttpContext.Server.MapPath("../Images/Player_Shirts"),
                    jogador);

                AppServices.AddJogador(jogador);

                return RedirectToAction("Jogadores");
            }
            catch
            {
                return View(new JogadorModels());
            }
        }

        //
        // GET: /Admin/Edit/5

        public ActionResult EditJogador(int id)
        {
            JogadorModels jm = new JogadorModels();
            jm.Jogador = AppServices.GetJogador(id);
            return View(jm);
        }

        //
        // POST: /Admin/Edit/5

        [HttpPost]
        public ActionResult EditJogador(int id, Jogador jogador)
        {
            try
            {
                Jogador oldJogador = AppServices.GetJogador(jogador.idJogador);

                if (oldJogador.nome != jogador.nome || oldJogador.avatar != jogador.avatar)
                {
                    DataUtils.DeleteShirt(jogador.nomeShirt);
                    jogador.nomeShirt = DataUtils.CreateJogadorShirt(
                        HttpContext.Server.MapPath("~/Images/Player_Shirts"),
                        jogador);
                }

                AppServices.EditJogador(jogador);

                return RedirectToAction("Jogadores");
            }
            catch
            {
                JogadorModels jm = new JogadorModels();
                jm.Jogador = jogador;
                return View(jm);
            }
        }

        //
        // GET: /Admin/Delete/5

        public ActionResult DeleteJogador(int id)
        {
            return View(AppServices.GetJogador(id));
        }

        //
        // POST: /Admin/Delete/5

        [HttpPost]
        public ActionResult DeleteJogador(int id, string nomeShirt)
        {
            try
            {
                AppServices.RemoveJogador(id);
                DataUtils.DeleteShirt(nomeShirt);

                return RedirectToAction("Jogadores");
            }
            catch
            {
                return View(AppServices.GetJogador(id));
            }
        }

        public ActionResult RemoveJogadorFromTeam(int id)
        {
            return View(AppServices.GetJogador(id));
        }

        [HttpPost]
        public ActionResult RemoveJogadorFromTeam(int id, FormCollection collection)
        {
            try
            {
                AppServices.RemoveJogadorFromTeam(id, collection["Notas"]);

                return RedirectToAction("Jogadores");
            }
            catch
            {
                return View(AppServices.GetJogador(id));
            }
        }

        //**************************************// EQUIPAS //**************************************//

        //
        // GET: /Admin/Jogadores/

        public ActionResult Equipas()
        {
            return View(AppServices.GetAllEquipasActivas());
        }

        //
        // GET: /Admin/Create

        public ActionResult CreateEquipa()
        {
            return View();
        }

        //
        // POST: /Admin/Create

        [HttpPost]
        public ActionResult CreateEquipa(Equipa equipa, HttpPostedFileBase image)
        {
            try
            {
                if(image != null) 
                    equipa.logo = DataUtils.CreateTeamLogo(image);
                AppServices.AddEquipa(equipa);

                return RedirectToAction("Equipas");
            }
            catch
            {
                return View(equipa);
            }
        }

        //
        // GET: /Admin/Edit/5

        public ActionResult EditEquipa(int id)
        {
            return View(AppServices.GetEquipa(id));
        }

        //
        // POST: /Admin/Edit/5

        [HttpPost]
        public ActionResult EditEquipa(int id, Equipa equipa, HttpPostedFileBase image)
        {
            try
            {
                if(image != null)
                    equipa.logo = DataUtils.CreateTeamLogo(image);
                AppServices.EditEquipa(equipa);

                return RedirectToAction("Equipas");
            }
            catch
            {
                return View(equipa);
            }
        }

        //
        // GET: /Admin/Delete/5

        public ActionResult DeleteEquipa(int id)
        {
            return View(AppServices.GetEquipa(id));
        }

        //
        // POST: /Admin/Delete/5

        [HttpPost]
        public ActionResult DeleteEquipa(int id, string logo)
        {
            try
            {
                //if(AppServices.GetJogosWhere(c => c.idEquipaCasa == id || c.idEquipaFora == id).Size > 0)
                // return View("UnremovableEquipa");
                AppServices.RemoveEquipa(id);
                DataUtils.DeleteTeamLogo(logo);

                return RedirectToAction("Equipas");
            }
            catch
            {
                return View(AppServices.GetEquipa(id));
            }
        }

        //
        // GET: /Admin/Delete/5

        public ActionResult DeactivateEquipa(int id)
        {
            return View(AppServices.GetEquipa(id));
        }

        //
        // POST: /Admin/Delete/5

        [HttpPost]
        public ActionResult DeactivateEquipa(int id, string logo)
        {
            try
            {
                AppServices.RemoveEquipa(id);
                DataUtils.DeleteTeamLogo(logo);

                return RedirectToAction("Equipas");
            }
            catch
            {
                return View(AppServices.GetEquipa(id));
            }
        }


        //************************************// COMPETICOES //************************************//


        public ActionResult Competicoes()
        {
            return View(AppServices.GetActiveCompeticoes());
        }

        public ActionResult CreateCompeticao()
        {
            return View();
        }

        //
        // POST: /Admin/Create

        [HttpPost]
        public ActionResult CreateCompeticao(Competicao competicao, HttpPostedFileBase image)
        {
            try
            {
                if (image != null)
                    competicao.imagem = DataUtils.CreateCompeticaoLogo(image);
                AppServices.AddCompeticao(competicao);

                return RedirectToAction("Competicoes");
            }
            catch
            {
                return View(competicao);
            }
        }

        //
        // GET: /Admin/Edit/5

        public ActionResult EditCompeticao(int id)
        {
            return View(AppServices.GetCompeticao(id));
        }

        //
        // POST: /Admin/Edit/5

        [HttpPost]
        public ActionResult EditCompeticao(int id, Competicao competicao, HttpPostedFileBase image)
        {
            try
            {
                if (image != null)
                    competicao.imagem = DataUtils.CreateCompeticaoLogo(image);
                AppServices.EditCompeticao(competicao);

                return RedirectToAction("Competicoes");
            }
            catch
            {
                return View(competicao);
            }
        }
    }
}

AnatidaeHaxball/Controllers/ApresentacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AnatidaeHaxball.Controllers
{
    public class ApresentacaoController : Controller
    {
        //
        // GET: /Apresentacao/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Apresentacao/Contactos

        public ActionResult Contactos()
        {
            return View();
        }

        //
        // GET: /Apresentacao/Equipamentos

        public ActionResult Equipamentos()
        {
            return View();
        }

       
    }
}

AnatidaeHaxball/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Anatidae Haxball</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />

        @Styles.Render("~/Content/Admin_css")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/modernizr")

        @RenderSection("head", required: false)

    </head>
    <body>
        
        <div id="admin_left_menu">
            @Html.ActionLink("Jogadores", "Jogadores", "Admin")
            @Html.ActionLink("Equipas", "Equipas", "Admin")
            @Html.ActionLink("Competições", "Competicoes", "Admin")
        </div>
        <div class="floater"></div>
        <div class="page_title">@ViewBag.Title</div>
        @RenderSection("top_menu", required: false)
        <div class="center">
            @RenderBody()
        </div>

        @RenderSection("scripts", required: false)




    </body>
</html>

AnatidaeHaxball/Views/Shared/_DeleteEquipa.cshtml
@using AnatidaeHaxball
@model AnatidaeHaxball.Equipa

<fieldset>
    <legend>Equipa</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.tag)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.tag)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.nome)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.nome)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.logo)
    </div>
    <div class="display-field">
        <img height="150" src="@DataUtils.GetTeamLogo(Model.logo)" />
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        @Html.HiddenFor(model => model.logo)

        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Equipas")
    </p>
}

AnatidaeHaxball/Views/Shared/_DeleteJogador.cshtml
@model AnatidaeHaxball.Jogador

<fieldset>
    <legend>Jogador</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.nome)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.nome)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.avatar)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.avatar)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.posicao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.posicao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ave)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ave)
    </div>
</fieldset>

AnatidaeHaxball/Views/Shared/_EditOrCreateCompeticao.cshtml
@using AnatidaeHaxball.HtmlHelpers
@model AnatidaeHaxball.Competicao


@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Competicao</legend>

        @Html.HiddenFor(model => model.competicaoID)
        @Html.HiddenFor(model => model.activa)
        @Html.HiddenFor(model => model.imagem)

        <div class="editor-label">
            @Html.LabelFor(model => model.nome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nome)
            @Html.ValidationMessageFor(model => model.nome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.edicao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.edicao)
            @Html.ValidationMessageFor(model => model.edicao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.link)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.link)
            @Html.ValidationMessageFor(model => model.link)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.imagem)
        </div>
        <div class="editor-field">
            @if (Model != null && !String.IsNullOrEmpty(Model.imagem))
            {
                <img height="150" src="@AnatidaeHaxball.DataUtils.GetTeamLogo(Model.imagem)" /><br />
            }
                
            @Html.InputImage()
            @Html.ValidationMessageFor(model => model.imagem)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Ver Competições", "Competicoes")
</div>


AnatidaeHaxball/Views/Shared/_EditOrCreateEquipa.cshtml
@using AnatidaeHaxball.HtmlHelpers
@model AnatidaeHaxball.Equipa

@using (Html.BeginForm(Html.CurrentAction(), "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Equipa</legend>

        @Html.HiddenFor(model => model.idEquipa)
        @Html.HiddenFor(model => model.activa)
        @Html.HiddenFor(model => model.logo)

        <div class="editor-label">
            @Html.LabelFor(model => model.tag)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.tag)
            @Html.ValidationMessageFor(model => model.tag)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.nome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nome)
            @Html.ValidationMessageFor(model => model.nome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.logo)
        </div>
        <div class="editor-field">
            @if(Model != null && !String.IsNullOrEmpty(Model.logo)){
                <img height="150" src="@AnatidaeHaxball.DataUtils.GetTeamLogo(Model.logo)" /><br />
            }
                
            @Html.InputImage()
            @Html.ValidationMessageFor(model => model.logo)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Equipas")
</div>

AnatidaeHaxball/Views/Shared/_EditOrCreateJogador.cshtml
@model AnatidaeHaxball.Models.JogadorModels

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Jogador</legend>

        @Html.HiddenFor(model => model.Jogador.idJogador)
        @Html.HiddenFor(model => model.Jogador.nomeShirt)
        @Html.HiddenFor(model => model.Jogador.naEquipa)

        <div class="editor-label">
            @Html.LabelFor(model => model.Jogador.nome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Jogador.nome)
            @Html.ValidationMessageFor(model => model.Jogador.nome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Jogador.avatar)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Jogador.avatar)
            @Html.ValidationMessageFor(model => model.Jogador.avatar)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Jogador.posicao)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Jogador.posicao, new SelectList(Model.Posicoes, "Id", "Name"))
            @Html.ValidationMessageFor(model => model.Jogador.posicao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Jogador.ave)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Jogador.ave)
            @Html.ValidationMessageFor(model => model.Jogador.ave)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Jogadores")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AnatidaeHaxball/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Anatidae Haxball</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        <meta name="description" content="Página Web da Equipa Anatidae Haxball">
        <meta name="keywords" content="anatidae, haxball">

        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/modernizr")

        @RenderSection("head", required: false)

    </head>
    <body>
        
        <div class="floater"></div>
        <div class="page_title">@ViewBag.Title</div>
        @RenderSection("top_menu", required: false)
        <div class="center">
            @RenderBody()
        </div>


@*        @RenderSection("scripts", required: false)*@

        <script type="text/javascript">
            /*<![CDATA[*/
            $.fn.vAlign = function () {
                return this.each(function () {
        	        $(".floater").css('margin-top', (-Math.ceil($(this).height() / 2) - 81) + "px"); //-81 é a metade da altura do menu
                });
            };

            $(".center").vAlign();
            /*]]>*/
        </script>

        <div class="black_bar">
	        <ul id="main_menu" >
		        <li id="his">@Html.ActionLink("Apresentação", "Index", "Apresentacao")</li>
		        <li id="stats">@Html.ActionLink("Estatísticas", "Index", "Estatisticas")</li>
		        <li id="chat">@Html.ActionLink("Chat", "Index", "Chat")</li>
		        <li id="cal">@Html.ActionLink("Calendário", "Index","Calendario")</li>
		        <li id="plantel">@Html.ActionLink("Plantel", "Index","Plantel")</li>
		        <li id="compet">@Html.ActionLink("Competições", "Index","Competicoes")</li>
		        <li id="logo">@Html.ActionLink("Logo", "Index", "Home")</li>
	        </ul>
        </div>

    </body>
</html>